name: Basic Checks

on: [push]

jobs:
    unit-tests:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Environment 
        run: npm install

      - name: Run Unit tests
        run: npm run test

      - name: Linter Failed 
        if: failure()
        run: curl -d "content=Unit test has failed" https://discord.com/api/webhooks/1256687026250584084/ZtyedEy73Vpvb4yW10HZV_W8PsJT-DxtZbXjCMO4KhJ5D51fY1BMr5BC00PpvQJsrHFa


    linter:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure Environment 
        run: npm install

      - name: Run Unit tests
        run: npm run lint

      - name: Linter Failed 
        if: failure()
        run: curl -d "content=Linter has failed" https://discord.com/api/webhooks/1256687026250584084/ZtyedEy73Vpvb4yW10HZV_W8PsJT-DxtZbXjCMO4KhJ5D51fY1BMr5BC00PpvQJsrHFa